### ISSUE TITLE
get_session_state

### ISSUE THREAD

**Issue by gusDuarte** [sugarlabs/browse-activity#30]
I'm testing webkit2 branch, and I found the following excpeption.

File "/usr/share/sugar/activities/Browse.activity/webactivity.py", line 492, in write_file
    self._tabbed_view.get_state()
  File "/usr/share/sugar/activities/Browse.activity/browser.py", line 464, in get_state
    'state': tab_page.browser.get_state()})
  File "/usr/share/sugar/activities/Browse.activity/browser.py", line 700, in get_state
    state = self.get_session_state()
AttributeError: 'Browser' object has no attribute 'get_session_state'

Attached you can find the log file.
[org.laptop.WebActivity-1.txt](https://github.com/sugarlabs/browse-activity/files/222808/org.laptop.WebActivity-1.txt)

**Comment by samdroid-apps** [comment]
Hello!

What version of WebKit2 are you using?

Its probably packaged as webkitgtk4.

Thanks,
Sam

**Comment by quozl** [comment]
@samdroid-apps, name as packaged depends on distribution.  The log shows *dist-packages* instead of *site-packages* in the *sugar3* path, so the test was on a Debian or Debian-based distribution. The lack of gi versioning warnings also suggests a much older gi.

**Comment by gusDuarte** [comment]
Hi,
Thanks for your quickly response, i forgot mention, i'm testing on Ubuntu
14.04.

So, if i understand well, the problem is the older gi version ?

Do you know how i can upgrade the gi package ?

Thanks.

Gustavo.

**Comment by samdroid-apps** [comment]
Hi,

An old GI version is just a symptom of the problem.  The issue is caused by an old WebKit version.  It would be very unlikely to have a 2+ year old GI version and a brand new WebKit on the same system.

To fix it, you need to update your system.  In the fedora world, this needs Fedora 24 Alpha, or newer (rawhide).  I'm not sure what webkit is in Ubuntu 16.04, but I believe is is still too old.

This is the WebKit version required (it adds the session state api): http://webkitgtk.org/2016/03/22/webkitgtk2.12.0-released.html

**Comment by gusDuarte** [comment]
@samdroid-apps, i understand, i'll try install the latest webkit on the system.

Many thanks.

**Comment by quozl** [comment]
I've tested WebKit 2.12 on Ubuntu 16.04 with Browse-158 and it works well.

**Comment by gusDuarte** [comment]
Good news!!

Thanks James.

**Comment by davelab6** [comment]
@gusDuarte can this be closed?

**Comment by gusDuarte** [comment]
Yes sure.!!
Thanks
