### ISSUE TITLE
[Feature]: 'download complete' should replace 'download started' on completion

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/browse-activity#72]
**Steps to reproduce:**
 - Open a webpage
 - Download a file (small enough to be download in ~5 sec)

**Observed Result:**
 - `download started` alert is present even after `download completed`

**Proposed Result:**
 - `download started` should be replaced by `Download completed` on completion
 - as implemented in 19c0ad7

Kindly review this issue, since I am unaware if the present implementation was intentional

**Comment by quozl** [comment]
Yes, I'm aware of this behaviour, and I seem to recall it was because quickly switching from _started_ to _completed_ may be disconcerting to young learners.  Truthfully the download is still _started_ even though it is _completed_ already.

It may be wrong to continue to say _started_ after the _completed_ alert is dismissed.  So I'd like to see the _started_ alert removed when the _completed_ alert is removed by either timeout or button.

@walterbender, what do you think?

**Comment by Pro-Panda** [comment]
Sorry if I am misunderstanding,
> It may be wrong to continue to say started after the completed alert is dismissed. So I'd like to see the started alert removed when the completed alert is removed by either timeout or button.

The curent implementation displays `comepleted` alert only after download is completed and `started` alert is removed. Hence, started alert would be absent even before `completed` alert is visible

**Comment by quozl** [comment]
@Pro-Panda, not sure what you mean by thumbs-up; are you okay with the current behaviour?

**Comment by Pro-Panda** [comment]
@quozl, 
no Sorry
That was meant as a Thanks for letting me know this
> The completion is also indicated by the download progress icon on the toolbar.

[Removed to avoid confusion to others as well]

**Comment by Pro-Panda** [comment]
**My opinion**: 
we should instantly switch from `completed` to `started`

**Reason:** 
 - avoid inconsistency by saying that `Download started` and download icon showing its completed(for a download that takes <9 sec)
 - The user should be updated if the download has completed instantly

**Note:**
Since I have not observed sugar users, and their way of using sugar, I wouldn't be a good judge on this. But I am assuming that users would understand and adapt to this update with time.

**Comment by quozl** [comment]
From `completed` to `started` or from `started` to `completed`?

**Comment by Pro-Panda** [comment]
Updated, apologies. :disappointed:

**Comment by quozl** [comment]
Thanks.  On the other hand, an adaption argument works both ways; we have an installed-base of users who have adapted to what we have now.

We need consensus.  Others please state your preference?

Also, perhaps it should be
* "Downloading" or "Download in progress" rather than "Download started", and;
* "Downloaded"  or "Download finished" rather than "Download completed".

**Comment by quozl** [comment]
We've waited a couple of weeks and no other input.  Given lack of others preferences, what do you think of;

* "Downloading", and;
* "Downloaded".

That is, a "Downloading" alert is shown.

If the user ignores the "Downloading" alert, then when the download is finished the alert title is changed to "Downloaded".

If the user dismisses the "Downloading" alert, then when the download is finished a new alert "Downloaded" is shown.  During this time the download progress icon fills.

Also, while the "Downloading" alert is visible, the alert may indicate progress as a percentage.

**Comment by Pro-Panda** [comment]
I remember replying to this thread(not sure what happened),
I agree with all the mentioned points

**Comment by quozl** [comment]
Thanks.

**Comment by aarjavjain1** [comment]
I have worked on this feature and I think I have successfully implemented it. Should I make a PR?

**Comment by quozl** [comment]
Up to you.  I can't see any commits in your fork of Browse.  I can't promise to not find any problem.  :grin:

You might also consider
* running `setup.py genpot` to update the translatable strings,
* providing human translations for any languages you share access to,
* visiting https://translate.sugarlabs.org/ to assess opportunities to contribute.

**Comment by aarjavjain1** [comment]
@quozl I have updated the code on my fork in the branch `2019-03-18-Download-Alert`. Please have a look.

`https://github.com/aarjavjain1/browse-activity/tree/2019-03-18-Download-Alert`

Thanks.

**Comment by aarjavjain1** [comment]
Sorry, I have updated the code. https://github.com/aarjavjain1/browse-activity/commit/2d7771961fde6ab1587770f2b488ffdd2ce41732

Please review and suggest changes. Thanks.

**Comment by quozl** [comment]
Thanks.  Reviewed and merged with 19c0ad781e755af2c4a734c94d516bd305c4b5d0 above.  Also cleared `_start_alert` when it is removed, so the remove does not happen twice.  Please test 18bd835.
