### ISSUE TITLE
Enhance browser homepage 

### ISSUE THREAD

**Issue by perriefidelis** [sugarlabs/browse-activity#87]
<img width="1440" alt="screenshot 2019-02-02 at 4 48 40 pm" src="https://user-images.githubusercontent.com/30669761/52166370-b027cd00-270c-11e9-93f3-b0707fcbf78c.png">
In the current browser homepage text space and search button seems too small, creating constrains of having a good space to type and good button size to click on with ease.

I,
- Increased the size of the text space 
- Increased the size of the 'google search' button
- Change the colour of the button
- Centralised the logo, text space and button, to maintain a better use of white spacing
- Added a console, so once you're on you don't need to click first before typing... just start typing

![browse](https://user-images.githubusercontent.com/30669761/52166449-a8b4f380-270d-11e9-9d13-4de273251aba.png)

**Comment by manangoel99** [comment]
Can I take up this issue?

**Comment by pro-panda** [comment]
Please note there is no need to ask permission to work on an issue. See our [guide to contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing). 
#88 was an attempt in progress to fix the issue, but you can submit your changes as well, Sugar Labs is a meritocracy

**Comment by quozl** [comment]
In the initial screenshot, Browse is not taking enough space for the toolbar.  As if the style cell size is wrong, and the display resolution is very high.  I've checked the screenshot size, and it is 2880 x 1800 pixels.  Sugar was designed for 1200 x 900 pixel resolution and has not been fully adapted to larger resolutions.  SUGAR_SCALING environment variable may have to be changed, but we don't have a user interface for changing it.  As part of the adaption to varied and larger resolutions, the Browse default page styles will have to change to be based on percentages of width and height rather than pixels.
